gyro_noise: 0.01
acc_noise: 0.48
gyro_bias_noise: 0.0000001
acc_bias_noise: 0.02
uwb_noise: 0.1
trajectory_noise: 0.2
non_hol_noise_z: 0.05
room_0_x: -5
room_0_y: -5
corridor_0_x_0: -7
corridor_0_x_1: -5
corridor_0_y_0: -4.3
corridor_0_y_1: 14
corridor_1_x_0: -14
corridor_1_x_1: -5
corridor_1_y_0: 14
corridor_1_y_1: 17
corridor_2_x_0: -15.5
corridor_2_x_1: -12
corridor_2_y_0: -4.3
corridor_2_y_1: 14
room_1_x: -4.5
room_1_y: -4.3
glass_room_x_0: -10
glass_room_x_1: -5
glass_room_y_0: -6
glass_room_y_1: -4.3
glass_room_0_x_0: -11
glass_room_0_x_1:  -8
glass_room_0_y_0: -6
glass_room_0_y_1: -4.3
